[.axoniq-feature]
= Axon Framework 5.0 to Axoniq Framework Migration
:navtitle: Axon Framework 5.0 to Axoniq Framework Migration

Axon Framework 5.1 extracts several production components into a dedicated commercial artifact: *Axoniq Framework* (`io.axoniq.framework`).
Users on Axon Framework 5.0 who used features like Axon Server connectivity, distributed messaging or the Axon Server Testcontainer for testing need to update their dependencies and package imports.

Production use of these components additionally requires a license you can obtain via the https://platform.axoniq.io[AxonIQ Platform].
Smaller organizations may be eligible for complimentary access to these components, for more information reach out to https://www.axoniq.io/contact[our sales team].

The following table summarizes the components affected by the reorganization of features:

[cols="1,2,2"]
|===
| Component | Axon Framework 5.0 module | Axoniq Framework 5.1 module

| Axon Framework BOM
| `org.axonframework:axon-framework-bom`
| `io.axoniq.framework:axoniq-framework-bom`

| Axon Spring Boot Starter
| `org.axonframework.extensions.spring:axon-spring-boot-starter`
| `io.axoniq.framework:axoniq-spring-boot-starter`

| Axon Server connector
| `org.axonframework:axon-server-connector`
| `io.axoniq.framework:axon-server-connector`

| Distributed messaging
| `org.axonframework:axon-messaging`
| `io.axoniq.framework:axoniq-distributed-messaging`

| Axon Server Testcontainer (split from `axon-test`)
| `org.axonframework:axon-test` (`AxonTestFixture` remains here)
| `io.axoniq.framework:axoniq-testcontainer` (`AxonServerContainer` moves here)

|===

[#dependency-management]
== Dependency management

If you are using the xref:ROOT:modules.adoc#axon-framework-bom[Axon Framework BOM], you can replace it with the xref:ROOT:modules.adoc#advanced-framework-bom[*Axoniq* Framework BOM] in your dependency management to keep module versions aligned.
The Axoniq Framework BOM includes all Axon Framework BOM dependencies, so you do not need to include both.

[tabs]
====
Maven::
+
--

[source,xml]
----
<!--...-->
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.axoniq.framework</groupId>
            <artifactId>axoniq-framework-bom</artifactId>
            <version>${version.axon}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

        ...

    </dependencies>
</dependencyManagement>
<!--...-->
----
--

Gradle::
+
--
[source,groovy]
----
implementation(platform("io.axoniq.framework:axoniq-framework-bom:<VERSION>"))
----
--
====

If you were using the link:https://central.sonatype.com/artifact/org.axonframework.extensions.spring/axon-spring-boot-starter[Axon Spring Boot Starter], you can use the link:https://central.sonatype.com/artifact/io.axoniq.framework/axoniq-spring-boot-starter[Axoniq Spring Boot Starter] as a drop-in replacement, since it includes the Axon Spring Boot Starter entirely.

[tabs]
====
Maven::
+
[source,xml]
----
<!-- Old -->
<dependency>
    <groupId>org.axonframework.extensions.spring</groupId>
    <artifactId>axon-spring-boot-starter</artifactId>
</dependency>

<!-- Drop-In replacement -->
<dependency>
    <groupId>io.axoniq.framework</groupId>
    <artifactId>axoniq-spring-boot-starter</artifactId>
</dependency>
----

Gradle::
+
[source,groovy]
----
// Old
implementation 'org.axonframework.extensions.spring:axon-spring-boot-starter'

// Drop-In replacement
implementation 'io.axoniq.framework:axoniq-spring-boot-starter'
----
====

[#licensing]
== Licensing

The Axoniq Framework features are commercial offerings requiring a license for production use.
Licenses can be obtained through the https://platform.axoniq.io[AxonIQ Platform].

For configuring credentials, evaluating for free, feature entitlement, message throughput limits, and pricing, see the
xref:axoniq-platform-reference:ROOT:licensing/index.adoc[Axoniq Platform licensing reference].


[#axon-server-connector]
== Axon Server connector

The Axon Server connector module has moved to Axoniq Framework.
To migrate you need to replace the Axon Framework 5.0 dependency with the Axoniq Framework 5.1 one:

[tabs]
====
Maven::
+
[source,xml]
----
<!-- Remove -->
<dependency>
    <groupId>org.axonframework</groupId>
    <artifactId>axon-server-connector</artifactId>
</dependency>

<!-- Add -->
<dependency>
    <groupId>io.axoniq.framework</groupId>
    <artifactId>axon-server-connector</artifactId>
</dependency>
----

Gradle::
+
[source,groovy]
----
// Remove
implementation 'org.axonframework:axon-server-connector'

// Add
implementation 'io.axoniq.framework:axon-server-connector'
----
====

If you have switched to using the Axoniq Spring Boot Starter dependency, you can omit the dependency, since it includes the Axon Server connector as the default connector.

Along with the maven module move, also the package structure of the Axon Server connector changed.
First of all, the root package changed from `org.axonframework.axonserver.connector` to `io.axoniq.framework.axonserver.connector`.
Apart from that, we also introduced an `io.axoniq.framework.axonserver.connector.api` package for more clarity.
Consult the table below on details about what moved where:

[cols="1,1,1"]
|===
| Axon Framework 5.0 | Axoniq Framework 5.1 | Most Notable changes

| `o.a.a.connector`
| `i.a.f.a.connector`
| Root package renamed

| `o.a.a.connector.*`
| `i.a.f.a.connector.api.*`
| `AxonServerConfiguration`, `AxonServerConnectionManager`, `AxonServerException`, `ConnectionManager` and `TagsConfiguration` moved to `*.api` subpackage

| `o.a.a.connector.*`
| `i.a.f.a.connector.shared.*`
| `ErrorCode` and `MetadataConverter` moved to `*.shared` subpackage

| `o.a.a.connector.util.*`
| `i.a.f.a.connector.shared.*`
| `ExceptionConverter` and `GrpcExceptionParser` moved to `*.shared` subpackage

| `o.a.a.connector.command.*`
| `i.a.f.a.connector.api.command.*`
| all `Exceptions` moved to the `*.api.command` subpackage

| `o.a.a.connector.query.*`
| `i.a.f.a.connector.api.query.*`
| all `Exceptions` moved to the `*.api.query` subpackage

|===

[#distributed-messaging]
== Distributed messaging

`DistributedCommandBus` and `DistributedQueryBus`, along with their configuration records, have moved from `axon-messaging` to the dedicated `axoniq-distributed-messaging` module.

Add the new dependency:

[tabs]
====
Maven::
+
[source,xml]
----
<dependency>
    <groupId>io.axoniq.framework</groupId>
    <artifactId>axoniq-distributed-messaging</artifactId>
</dependency>
----

Gradle::
+
[source,groovy]
----
implementation 'io.axoniq.framework:axoniq-distributed-messaging'
----
====

Along with the maven module move, also the package structure changed, so you need to update any use of the following packages:

[cols="1,1"]
|===
| Axon Framework 5.0 | Axoniq Framework 5.1

| `org.axonframework.messaging.commandhandling.distributed`
| `io.axoniq.framework.messaging.commandhandling.distributed`

| `org.axonframework.messaging.queryhandling.distributed`
| `io.axoniq.framework.messaging.queryhandling.distributed`

|===

Apart from that package move, the field names and method signatures of classes within those packages remain unchanged.

[#axon-server-testcontainer]
== Axon Server testcontainer

`AxonServerContainer` has moved from `axon-test` to a dedicated `axoniq-testcontainer` module.
To continue using it, add the new dependency and update the import.
Be sure to keep the `org.axonframework:axon-test` dependency if you want to continue using the `AxonTestFixture`.

[tabs]
====
Maven::
+
[source,xml]
----
<!-- Add -->
<dependency>
    <groupId>io.axoniq.framework</groupId>
    <artifactId>axoniq-testcontainer</artifactId>
    <scope>test</scope>
</dependency>
----

Gradle::
+
[source,groovy]
----
// Add
testImplementation 'io.axoniq.framework:axoniq-testcontainer'
----
====

Update the imports:

[cols="1,1"]
|===
| Axon Framework 5.0 | Axoniq Framework 5.1

| `org.axonframework.test.server.AxonServerContainer`
| `io.axoniq.framework.testcontainer.AxonServerContainer`

| `org.axonframework.test.server.AxonServerContainerUtils`
| `io.axoniq.framework.testcontainer.AxonServerContainerUtils`

|===