<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2010-2026. AxonIQ B.V.
  ~
  ~ Licensed under the AXONIQ SOFTWARE SUBSCRIPTION AGREEMENT TERMS,
  ~ Version September 2025 (the "License");
  ~ The software is available under Non-Production Free License.
  ~ Production use requires a paid license. See the License for the
  ~ specific language governing permissions and limitations under
  ~ the License.
  ~
  ~ You may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at:
  ~
  ~    https://www.axoniq.io/legal/terms-of-service
  ~
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.axoniq.framework</groupId>
        <artifactId>axoniq-framework-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../build/parent/pom.xml</relativePath>
    </parent>

    <artifactId>axoniq-workflow-parent</artifactId>
    <packaging>pom</packaging>

    <name>Axoniq Framework - Workflow - Parent</name>
    <description>
        Workflows provide a durable execution module with a configurable DSL, based on Axon Framework's event sourcing
        logic.
    </description>

    <modules>
        <module>axoniq-workflow-dsl</module>
        <module>axoniq-workflow-dsl-kotlin</module>
        <module>axoniq-workflow-engine</module>
        <module>axoniq-workflow-spring-boot</module>
        <module>axoniq-workflow-spring-boot-kotlin</module>
        <module>axoniq-workflow-test</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-messaging</artifactId>
        </dependency>
        <dependency>
            <groupId>io.axoniq.license</groupId>
            <artifactId>entitlement-manager</artifactId>
        </dependency>
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-eventsourcing</artifactId>
        </dependency>
        <dependency>
            <groupId>io.axoniq.framework</groupId>
            <artifactId>axoniq-event-streaming</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-common</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-messaging</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit5</artifactId>
        </dependency>
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
