spring:
  datasource:
    url: jdbc:h2:./examples/bike-rental/rental_db;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: bike-rental
  docker:
    compose:
      file: file:examples/bike-rental/docker-compose.yaml
      lifecycle-management: start_only
  main:
    web-application-type: reactive
axon:
  axonserver:
    enabled: true
springdoc:
  swagger-ui:
    try-it-out-enabled: true
