spring:
  datasource:
    url: jdbc:h2:./examples/bike-rental/rental_db;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: bike-rental
  docker:
    compose:
      file: file:examples/bike-rental/docker-compose.yaml
      lifecycle-management: start_only
  main:
    web-application-type: reactive
axon:
  axon-server:
    enabled: true
  eventhandling:
    processors:
      [io.axoniq.demo.bikerental.rental]:
          mode: POOLED
          initialSegmentCount: 1 # FIXME -> not working, still getting 16 segments
      [io.axoniq.demo.bikerental.payment]:
          mode: POOLED
          initialSegmentCount: 1 # FIXME -> not working, still getting 16 segments

springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
  api-docs:
    enabled: true
