<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2010-2026. AxonIQ B.V.
  ~
  ~ Licensed under the AXONIQ SOFTWARE SUBSCRIPTION AGREEMENT TERMS,
  ~ Version September 2025 (the "License");
  ~ The software is available under Non-Production Free License.
  ~ Production use requires a paid license. See the License for the
  ~ specific language governing permissions and limitations under
  ~ the License.
  ~
  ~ You may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at:
  ~
  ~    https://www.axoniq.io/legal/terms-of-service
  ~
  ~
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.axoniq.framework</groupId>
        <artifactId>axoniq-framework</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>axoniq-framework-bom</artifactId>

    <name>Axoniq Framework - Bill of Materials</name>
    <description>
        Bill of Materials providing all contained modules of the Axoniq Framework.
    </description>

    <packaging>pom</packaging>

    <dependencyManagement>
        <dependencies>
            <!-- Axon Framework -->
            <dependency>
                <groupId>org.axonframework</groupId>
                <artifactId>axon-framework-bom</artifactId>
                <version>${axon-framework.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Axoniq Framework: Connectors -->
            <dependency>
                <groupId>io.axoniq.framework</groupId>
                <artifactId>axoniq-postgresql</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.axoniq.framework</groupId>
                <artifactId>axoniq-server-connector</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- Axoniq Framework: Messaging -->
            <dependency>
                <groupId>io.axoniq.framework</groupId>
                <artifactId>axoniq-dead-letter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.axoniq.framework</groupId>
                <artifactId>axoniq-distributed-messaging</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.axoniq.framework</groupId>
                <artifactId>axoniq-event-streaming</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- Axoniq Framework: Spring -->
            <dependency>
                <groupId>io.axoniq.framework</groupId>
                <artifactId>axoniq-spring-boot-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>io.axoniq.framework</groupId>
                <artifactId>axoniq-spring-boot-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
