<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2010-2026. AxonIQ B.V.
  ~
  ~ Licensed under the AXONIQ TERMS OF SERVICE,
  ~ Version 29 April 2026 (the "License");
  ~
  ~ The software is available for evaluation use without registration.
  ~ Continued use beyond the evaluation period requires registration
  ~ and a commercial license. See the License for the specific language
  ~ governing permissions and limitations under the License.
  ~ You may not use this file except in compliance with the License.
  ~
  ~ You may obtain a copy of the License at:
  ~  https://www.axoniq.io/legal/terms-of-service
  ~
  ~ For licensing information and to register, visit:
  ~  https://www.axoniq.io/pricing
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.axoniq.framework</groupId>
        <artifactId>axoniq-framework-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../build/parent/pom.xml</relativePath>
    </parent>

    <artifactId>axoniq-integrationtests</artifactId>

    <name>Axoniq Framework - Integration Tests</name>
    <description>
        Module containing integration tests to run during the build of Axoniq Framework.
        Does not contain any production code.
    </description>

    <dependencies>
        <!-- Axon Framework -->
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-common</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-messaging</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-eventsourcing</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-integrationtests</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

        <!-- Axoniq Framework -->
        <dependency>
            <groupId>io.axoniq.framework</groupId>
            <artifactId>axon-server-connector</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.axoniq.framework</groupId>
            <artifactId>axoniq-dead-letter</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.axoniq.framework</groupId>
            <artifactId>axoniq-multi-tenancy</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.axoniq.framework</groupId>
            <artifactId>axoniq-multi-tenancy</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.axoniq.framework</groupId>
            <artifactId>axoniq-testcontainer</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- Reactive -->
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- Logging - (required due to different logging approach in Axon Framework test Jars) -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core-test</artifactId>
            <version>${log4j.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
            <version>${log4j.version}</version>
            <scope>test</scope>
        </dependency>
        <!-- Testing -->
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers-junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
            </plugin>

            <!-- Silence the AS download message -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>-Daxon.axonserver.suppressDownloadMessage=true</argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
