<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2010-2026. AxonIQ B.V.
  ~
  ~ Licensed under the AXONIQ TERMS OF SERVICE,
  ~ Version 29 April 2026 (the "License");
  ~
  ~ The software is available for evaluation use without registration.
  ~ Continued use beyond the evaluation period requires registration
  ~ and a commercial license. See the License for the specific language
  ~ governing permissions and limitations under the License.
  ~ You may not use this file except in compliance with the License.
  ~
  ~ You may obtain a copy of the License at:
  ~  https://www.axoniq.io/legal/terms-of-service
  ~
  ~ For licensing information and to register, visit:
  ~  https://www.axoniq.io/pricing
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.axoniq.framework</groupId>
        <artifactId>axoniq-framework</artifactId>
        <version>${revision}</version>
    </parent>

    <groupId>io.axoniq.framework.examples</groupId>
    <artifactId>axoniq-framework-examples</artifactId>
    <packaging>pom</packaging>

    <name>Axoniq Framework - Examples</name>
    <description>Collection of examples used for demonstration and test purposes.</description>

    <modules>
        <module>multi-tenancy-java</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.axoniq.framework</groupId>
                <artifactId>axoniq-framework-bom</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
