# Copyright (c) 2010-2026. AxonIQ B.V.
#
# Licensed under the AXONIQ TERMS OF SERVICE,
# Version 29 April 2026 (the "License");
#
# The software is available for evaluation use without registration.
# Continued use beyond the evaluation period requires registration
# and a commercial license. See the License for the specific language
# governing permissions and limitations under the License.
# You may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at:
#  https://www.axoniq.io/legal/terms-of-service
#
# For licensing information and to register, visit:
#  https://www.axoniq.io/pricing
spring:
  datasource:
    url: jdbc:h2:./examples/bike-rental/rental_db;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  application:
    name: bike-rental
  docker:
    compose:
      file: file:examples/bike-rental/docker-compose.yaml
      lifecycle-management: start_only
  main:
    web-application-type: reactive
axon:
  axon-server:
    enabled: true
  eventhandling:
    processors:
      [io.axoniq.demo.bikerental.rental]:
          mode: POOLED
          initialSegmentCount: 1 # FIXME -> not working, still getting 16 segments
      [io.axoniq.demo.bikerental.payment]:
          mode: POOLED
          initialSegmentCount: 1 # FIXME -> not working, still getting 16 segments

springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
  api-docs:
    enabled: true
