spring.main.web-application-type=none
spring.main.banner-mode=off
logging.level.root=WARN
logging.level.io.axoniq.shardlab=INFO
logging.level.io.axoniq.framework.workflow=INFO
logging.level.org.axonframework=INFO
spring.datasource.hikari.maximum-pool-size=20
