[#testing-with-axon-server-testcontainer]
== Tests with the Axon Server Testcontainer

https://testcontainers.com/[Testcontainers] is a library that provides lightweight, throwaway instances of databases, message brokers, and other services as Docker containers.
This makes it ideal for (integration) testing.
Axon provides a dedicated container for Axon Server, called the `AxonServerContainer`.
By adding this to your tests with the `@Container` annotation, it will be started automatically.

However, you will be required to take the host and port of the constructed container and inject them.
If you are using Spring Boot, be sure to jump to <<axon_server_with_spring_boot_and_serviceconnection,this>> example.
Otherwise, here's what you need to do to use The `axon-server-connector` module provides the `AxonServerContainer` for use with Testcontainers:

[source,java]
----
import io.axoniq.axonserver.connector.AxonServerConnection;
import io.axoniq.axonserver.connector.AxonServerConnectionFactory;
import io.axoniq.axonserver.connector.impl.ServerAddress;
import jakarta.annotation.Nonnull;
import io.axoniq.framework.axonserver.connector.api.AxonServerConfiguration;
import org.axonframework.common.configuration.ComponentRegistry;
import org.axonframework.common.configuration.ConfigurationEnhancer;
import org.axonframework.eventsourcing.configuration.EventSourcedEntityModule;
import org.axonframework.eventsourcing.configuration.EventSourcingConfigurer;
import org.axonframework.test.fixture.AxonTestFixture;
import org.axonframework.test.fixture.MessagesRecordingConfigurationEnhancer;
import io.axoniq.framework.testcontainer.AxonServerContainer;
import org.junit.jupiter.api.*;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers
class AccountAxonServerTest {

    @Container
    static AxonServerContainer axonServer = new AxonServerContainer();
    private static AxonServerConnection connection;

    private AxonTestFixture fixture;

    @BeforeAll
    static void beforeAll() {
        axonServer.start();
        ServerAddress address = new ServerAddress(axonServer.getHost(), axonServer.getGrpcPort());
        connection = AxonServerConnectionFactory.forClient("GameTest")
                                                .routingServers(address)
                                                .build()
                                                .connect("default");
    }

    @BeforeEach
    void setUp() {
        // The MessagesRecordingConfigurationEnhancer is required to allow verification to succeed for the fixture.
        // Will be resolved automatically by the test fixture combined with Spring soon.
        EventSourcingConfigurer configurer =
                EventSourcingConfigurer.create()
                                       .registerEntity(EventSourcedEntityModule.autodetected(
                                               String.class, Account.class
                                       ))
                                       .componentRegistry(registry -> registry
                                               .registerEnhancer(new MessagesRecordingConfigurationEnhancer())
                                               .registerEnhancer(serverConfigurationEnhancer())
                                       );

        fixture = AxonTestFixture.with(configurer);
    }

    public ConfigurationEnhancer serverConfigurationEnhancer() {
        return new ConfigurationEnhancer() {
            @Override
            public void enhance(@Nonnull ComponentRegistry registry) {
                registry.registerComponent(
                        AxonServerConfiguration.class,
                        c -> {
                            AxonServerConfiguration serverConfig = new AxonServerConfiguration();
                            serverConfig.setServers(
                                    axonServer.getHost() + ":" + axonServer.getGrpcPort()
                            );
                            return serverConfig;
                        }
                );
            }

            @Override
            public int order() {
                return Integer.MIN_VALUE;
            }
        };
    }

    @Test
    void testWithAxonServer() {
        fixture.given()
               .noPriorActivity()
               .when()
               .command(new CreateAccountCommand("account-1", 500.00))
               .then()
               .success()
               .events(new AccountCreatedEvent("account-1", 500.00));
    }

    @AfterEach
    void tearDown() {
        fixture.stop();
    }

    @AfterAll
    static void afterAll() {
        connection.disconnect();
        axonServer.stop();
    }
}
----

As shown above, we need to inject a `ConfigurationEnhancer` to enhance the `AxonServerConfiguration`.
Axon's configuration will pick this up and make the connection to the `AxonServerContainer` for message distribution and event storage.

[#axon_server_with_spring_boot_and_serviceconnection]
=== AxonServerContainer with Spring Boot and @ServiceConnection

Spring Boot has a Testcontainers specific dependency that provides the `@ServiceConnection` annotation.
This annotation can be attached to Testcontainers, which then will automatically configure the connection properties for you.
Thus, if we add the `@ServiceConnection` to the `AxonServerContainer` field, our test setup is greatly simplified compared to the <<testing-with-axon-server-testcontainer,declarative>> approach:

[source,java]
----
import org.axonframework.extension.springboot.test.AxonSpringBootTest;
import org.axonframework.test.fixture.AxonTestFixture;
import io.axoniq.framework.testcontainer.AxonServerContainer;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@AxonSpringBootTest
@Testcontainers
class AccountAxonServerAndSpringBootTest {

    @Container
    @ServiceConnection
    static AxonServerContainer axonServer = new AxonServerContainer();

    @Autowired
    private AxonTestFixture fixture;

    @Test
    void testWithAxonServer() {
        fixture.given()
               .noPriorActivity()
               .when()
               .command(new CreateAccountCommand("account-1", 500.00))
               .then()
               .success()
               .events(new AccountCreatedEvent("account-1", 500.00));
    }
}
----