/*
 * Copyright (c) 2010-2026. AxonIQ B.V.
 *
 * Licensed under the AXONIQ SOFTWARE SUBSCRIPTION AGREEMENT TERMS,
 * Version September 2025 (the "License");
 * The software is available under Non-Production Free License.
 * Production use requires a paid license. See the License for the
 * specific language governing permissions and limitations under
 * the License.
 *
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *    https://www.axoniq.io/legal/terms-of-service
 *
 *
 */

package org.axonframework.extension.springboot.service.connection;

import org.axonframework.test.server.AxonServerContainer;
import org.springframework.boot.testcontainers.service.connection.ContainerConnectionDetailsFactory;
import org.springframework.boot.testcontainers.service.connection.ContainerConnectionSource;

/**
 * ConnectionDetailsFactory class that recognizes TestContainer instances running Axon Server. It will use the port
 * mappings generated by the test container to generate a
 * {@link org.springframework.boot.autoconfigure.service.connection.ConnectionDetails} instance that provides the
 * correct connection information.
 *
 * @author Allard Buijze
 * @since 4.9.0
 */
public class AxonServerTestContainerConnectionDetailsFactory extends ContainerConnectionDetailsFactory<AxonServerContainer, AxonServerConnectionDetails> {

    public AxonServerTestContainerConnectionDetailsFactory() {
        super(ContainerConnectionDetailsFactory.ANY_CONNECTION_NAME,
              "org.axonframework.test.server.AxonServerContainer",
              "org.axonframework.axonserver.connector.AxonServerConnectionManager");
    }

    @Override
    protected AxonServerConnectionDetails getContainerConnectionDetails(ContainerConnectionSource<AxonServerContainer> source) {
        return new AxonServerContainerConnectionDetails(source);
    }

    private static final class AxonServerContainerConnectionDetails
            extends ContainerConnectionDetails<AxonServerContainer> implements AxonServerConnectionDetails {

        AxonServerContainerConnectionDetails(ContainerConnectionSource<AxonServerContainer> source) {
            super(source);
        }

        @Override
        public String routingServers() {
            return getContainer().getAxonServerAddress();
        }
    }
}
