/*
 * Copyright (c) 2010-2026. AxonIQ B.V.
 *
 * Licensed under the AXONIQ SOFTWARE SUBSCRIPTION AGREEMENT TERMS,
 * Version September 2025 (the "License");
 * The software is available under Non-Production Free License.
 * Production use requires a paid license. See the License for the
 * specific language governing permissions and limitations under
 * the License.
 *
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *    https://www.axoniq.io/legal/terms-of-service
 *
 *
 */

package org.axonframework.messaging.eventsourcing.eventstore.jdbc;

/**
 * Jdbc table factory for HSQL databases.
 *
 * @author Rene de Waele
 * @since 3.0
 */
public class HsqlEventTableFactory extends AbstractEventTableFactory {

    /**
     * Singleton HsqlEventTableFactory instance
     */
    public static final HsqlEventTableFactory INSTANCE = new HsqlEventTableFactory();

    /**
     * Default constructor of the factory
     */
    protected HsqlEventTableFactory() {
    }

    @Override
    protected String idColumnType() {
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0, INCREMENT BY 1)";
    }

    @Override
    protected String payloadType() {
        return "BLOB";
    }
}
