// TODO Axoniq feature
== Blacklisting events

[WARNING]
.Blacklisting events not available in Axon Framework 5.1
====
The Blacklisting feature is not yet available in Axon Framework 5.1.
It will eventually be reintroduced in a subsequent release of Axon Framework.
The documentation below describes the concepts for reference and future use.
====

In a heterogeneously distributed application landscape your event handling components might receive events they do not have actual event handling members for. That this occurs is completely fine; the chances of a single application handling the entirety of all existing events is really small. This fact however does open up the possibility for optimization by _blacklisting_ events.

To this end Axon has to option to automatically blacklist events it cannot handle. The Tracking Event Processor takes the lead in actual blacklisting, which it does by signaling the utilized event stream when none of its handlers can handle the event in question. The event stream provided by the Axon Server connection in turn implements the functionality to notify an Axon Server node that certain events cannot be handled by it.

By default, blacklisting is turned for an Axon client connected to Axon Server. To disable blacklisting, the `disableEventBlacklisting` property can be adjusted as follows:

==== Axon Configuration API

[source,java]
----
AxonServerConfiguration axonServerConfig = new AxonServerConfiguration();
axonServerConfig.setDisableEventBlacklisting(true);

Configurer configurer = 
    DefaultConfigurer.defaultConfiguration()
        .registerComponent(AxonServerConfiguration.class, c -> axonServerConfig);
----

==== Spring Boot auto configuration

[source,text]
----
axon.axonserver.disableEventBlacklisting=true
----

____

*Retrying Blacklisted Events*

The topology of Event Handlers might change in the lifecycle of a given application. This thus means that once blacklisted events might at a later stage do have Event Handler members present. To cover this scenario, Axon Server will periodically send over blacklisted events to refresh the blacklisted set.

____