[.axoniq-feature]
[#distributing_events]
== Distributing events

To distribute events between applications, it is important to know whether the applications belong to the same bounded context.
If you don't recognize this concept, we recommend reading the link:https://www.axoniq.io/concepts/domain-driven-design[Bounded Context] section first.
Applications within the same context "speak the same language."
In other words, they communicate using the same set of messages, and thus events.

As such, we can share the `EventStore's` data source between these applications.
We may thus achieve distribution by utilizing the source itself.

However, sharing the entire event API is not recommended whenever the applications do not belong to the same context.
Instead, we should protect the boundary of the contexts, except for some clearly defined cross-boundary messages.
Since accessing the same source isn't an option, we require a different solution to share events.

To distribute events between bounded contexts, you can use Axon Server's xref:axon-server-reference:ROOT:axon-server/administration/multi-context.adoc[] solution, for example.
The multi-context support requires application registration to specific contexts.
Axon's configuration API has the `ComponentFactory` to allow construction of specific infrastructure components.
The `AxonServerEventStorageEngineFactory` is provided out of the box, which gives users the ability to request a component of type `EventStorageEngine` with name `storageEngine@{context-name}`:

[source,java]
----
import io.axoniq.framework.axonserver.connector.event.AxonServerEventStorageEngine;
import org.axonframework.common.configuration.Configuration;
import org.axonframework.eventsourcing.eventstore.EventStorageEngine;

public class AxonConfig {

    public EventStorageEngine contextSpecificStorageEngine(Configuration configuration,
                                                           String context) {
        return configuration.getComponent(AxonServerEventStorageEngine.class, "storageEngine@" + context);
    }
}
----

The context-specific engine can, for example, be configured as the message source for a xref:event-processors/streaming.adoc[Streaming Processor] to start reading from.

Alternatively, you can use a message broker to distribute events between contexts.

Although this allows further event distribution, we still recommend consciously sharing _the correct_ events.
Ideally, we add a form of context mapping, like an anti-corruption layer, between the contexts.
In other words, we recommend using a separate component that maps the events from the local context to a shared language right before distribution.

For example, this mapper would publish the messages on the AMQP queue or Kafka topic.
When it comes to Axon Server, we could, for example, use a distinct shared/global context to contain the shared language.