/*
 * Copyright (c) 2010-2026. AxonIQ B.V.
 *
 * Licensed under the AXONIQ TERMS OF SERVICE,
 * Version 29 April 2026 (the "License");
 *
 * The software is available for evaluation use without registration.
 * Continued use beyond the evaluation period requires registration
 * and a commercial license. See the License for the specific language
 * governing permissions and limitations under the License.
 * You may not use this file except in compliance with the License.
 *
 * You may obtain a copy of the License at:
 *  https://www.axoniq.io/legal/terms-of-service
 *
 * For licensing information and to register, visit:
 *  https://www.axoniq.io/pricing
 */

package io.axoniq.framework.postgresql;

import org.axonframework.common.annotation.Internal;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.sql.DataSource;

/**
 * Creates the tables, sequence, and indices that {@link PostgresqlEventStorageEngine} relies on, if
 * they do not already exist.
 *
 * @author John Hendrikx
 * @since 5.2.0
 */
@Internal
final class PostgresqlSchemaInitializer {

    private PostgresqlSchemaInitializer() {
        // utility class
    }

    // TODO #7 Allow to configure tables, sequences and indices
    static void initialize(DataSource dataSource) {
        try (
            Connection connection = dataSource.getConnection();
            Statement statement = connection.createStatement();
        ) {
            statement.execute(
                """
                CREATE TABLE IF NOT EXISTS events (
                  global_index INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY -1),

                  timestamp TIMESTAMPTZ NOT NULL,
                  payload BYTEA,
                  metadata JSON NOT NULL,
                  identifier VARCHAR NOT NULL,
                  type VARCHAR NOT NULL,

                  -- keys
                  PRIMARY KEY (global_index)
                );

                CREATE TABLE IF NOT EXISTS tags (
                  global_index INT8 NOT NULL,

                  key VARCHAR NOT NULL,
                  value VARCHAR NOT NULL,

                  -- keys
                  PRIMARY KEY (key, value, global_index)
                );

                CREATE TABLE IF NOT EXISTS consistency_tags (
                  tag_hash INT4 NOT NULL,
                  global_index INT8 NOT NULL,

                  -- keys
                  PRIMARY KEY (tag_hash)
                );

                -- Create a sequence used for monotonic final global index values. Starts at 1.
                CREATE SEQUENCE IF NOT EXISTS events_monotonic_seq
                  INCREMENT BY 1
                  CACHE 1
                  OWNED BY events.global_index;

                -- BTREE index on global_index in consistency_tags (for faster finalizations)
                CREATE INDEX IF NOT EXISTS consistency_tags_global_index_idx
                  ON consistency_tags (global_index);

                -- BTREE index on global_index in tags (for faster finalizations)
                CREATE INDEX IF NOT EXISTS tags_global_index_idx
                  ON tags (global_index);
                """
            );

            connection.commit();
        }
        catch (SQLException e) {
            throw new IllegalStateException("Could not initialize database schema", e);
        }
    }
}
