name: Axoniq Framework

on:
  push:
    branches:
      - main
      - 'axoniq-5.*.x'
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: Test and Build on JDK ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - java-version: 21
            sonar-enabled: true
            deploy-enabled: true
          - java-version: 25
            sonar-enabled: false
            deploy-enabled: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
          cache: "maven"
          server-id: artifact-registry-snapshots
          server-username: ARTIFACT_REGISTRY_USERNAME
          server-password: ARTIFACT_REGISTRY_PASSWORD

      - name: Regular Build
        if: ${{ !matrix.sonar-enabled }}
        run: |
          ./mvnw -B -U -ntp -Dstyle.color=always clean verify \
          -Possrh -Pintegration-test -Djacoco.skip=true -Dsurefire.rerunFailingTestsCount=5 -Dfailsafe.rerunFailingTestsCount=5 \
          -Dparallel=classes -DthreadCount=1 -DforkCount=2
      - name: Build with Coverage reports
        if: matrix.sonar-enabled
        run: |
          ./mvnw -B -U -ntp -Dstyle.color=always clean verify \
          -Dcoverage -Dsurefire.rerunFailingTestsCount=5 -Dfailsafe.rerunFailingTestsCount=5 \
          -Dparallel=classes -DthreadCount=1 -DforkCount=2

      - name: Sonar Analysis
        if: false # matrix.sonar-enabled | disabled for the time being
        run: |
          ./mvnw -B -ntp -Dstyle.color=always org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=AxonFramework_AxonFramework \
          -Dsonar.organization=axonframework \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to Google Cloud
        if: success() && matrix.deploy-enabled
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GKE_CLOUD_DEV_SA_KEY }}

      - name: Set up Cloud SDK
        if: success() && matrix.deploy-enabled
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Artifact Registry
        if: success() && matrix.deploy-enabled
        run: |
          export ARTIFACT_REGISTRY_USERNAME=oauth2accesstoken
          export ARTIFACT_REGISTRY_PASSWORD=$(gcloud auth print-access-token)
          ./mvnw -B -U -ntp -Dstyle.color=always deploy -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify run to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: CAGSEC92A
          SLACK_COLOR: ${{ job.status }}
          SLACK_TOKEN:  ${{ secrets.SLACK_BOT_TOKEN }}