[.axoniq-feature]
== Axoniq Framework modules

Besides the open source Axon Framework, Axoniq provides the Axoniq Framework advanced features which are available for production use with a commercial license.

Depending on the exact needs of your project, you will need to include one or more of these modules.

.Commercially available Framework Modules Overview
[excalidraw]
....
include::partial$advanced-modules.excalidraw[]
....

[cols="<,<,<,^"]
|===
|Module |Artifact Id |Group Id |Maven Central

|<<Axoniq PostgreSQL>>            |`axoniq-postgresql`                    |`io.axoniq.framework` |https://central.sonatype.com/search?q=io.axoniq.framework%3Aaxoniq-postgresql[available]
|<<Axoniq Axon Server connector>> |`axon-server-connector`         |`io.axoniq.framework` |https://central.sonatype.com/search?q=io.axoniq.framework%3Aaxon-server-connector[available]
|<<Axoniq distributed messaging>> |`axoniq-distributed-messaging`  |`io.axoniq.framework` |https://central.sonatype.com/search?q=a:axoniq-distributed-messaging[available]
|<<Axoniq dead letter queue>>     |`axoniq-dead-letter-queue`      |`io.axoniq.framework` |https://central.sonatype.com/search?q=axoniq-dead-letter-queue[available]
|<<Axoniq message transformation>> |`axoniq-message-transformation` |`io.axoniq.framework` |https://central.sonatype.com/search?q=a:axoniq-message-transformation[available]
|<<Axoniq multi-tenancy>>          |`axoniq-multi-tenancy`          |`io.axoniq.framework` |https://central.sonatype.com/search?q=a:axoniq-multi-tenancy[available]
|<<Axoniq tracing OpenTelemetry>> |`axon-tracing-opentelemetry`    |`io.axoniq.framework` |https://central.sonatype.com/search?q=a:axon-tracing-opentelemetry[available]
|<<Axoniq Workflow Engine>> |`axon-workflow-runtime`    |`io.axoniq.framework.workflow` |https://central.sonatype.com/search?q=a:axon-workflow-runtime[available]
ifdef::data-protection[]
|<<Axoniq Data Protection>> |`axoniq-data-protection`    |`io.axoniq.framework` |https://central.sonatype.com/search?q=a:axoniq-data-protection[available]
endif::[]
|===

=== Axoniq PostgreSQL

This module provides a storage solution optimized for use with link:https://www.postgresql.org/[PostgreSQL] by taking advantage of PostgreSQL-specifics.
It supports the Dynamic-Consistency Boundary, just as Axon Server does

=== Axoniq Axon Server connector

This module provides infrastructure components that connect to Axon Server.

=== Axoniq distributed messaging

This module provides distributed variants for messaging components (namely `CommandBus` and `QueryBus`).

=== Axoniq dead letter queue

This module provides the dead letter queue functionality.

=== Axoniq message transformation

This module rewrites stored events as they are read, so handlers always receive the current version. It is the Axoniq Framework replacement for Axon Framework 4 upcasting.
See the xref:message-transformation:index.adoc[event transformation reference] to get started.

=== Axoniq multi-tenancy

This module lets a single application instance serve multiple tenants, separating tenant data in transit and at rest by mapping each tenant to a dedicated Axon Server context.
See the xref:multi-tenancy:index.adoc[multi-tenancy reference] to get started.

=== Axoniq tracing OpenTelemetry

This extension contains the components needed to xref:tracing:index.adoc[enable tracing with OpenTelemetry].

=== Axoniq Workflow Engine

This module provides the xref:workflows:index.adoc[Axoniq Workflow Engine], which allows users to express complex, long-running business processes in simple, imperative code.

ifdef::data-protection[]
include::modules-dataprotection.adoc[]
endif::[]
