[#advanced-framework-bom]
=== Advanced Axon Framework Bill of Materials

For the advanced framework, we provide a BOM under the `io.axoniq.framework` Group id as follows:

[cols="<,<,<,^"]
|===
|Module |Artifact Id |Group Id |Maven Central

|<<Advanced Axon Framework Bill of Materials>> |`axoniq-framework-bom` |`io.axoniq.framework` |https://central.sonatype.com/search?q=a:axoniq-framework-bom[available]
|===

For using the BOM, you would add the `axoniq-framework-bom` dependency to your dependency management system:

[tabs]
====
Maven::
+
--

[source,xml]
----
<!--...-->
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.axoniq.framework</groupId>
            <artifactId>axoniq-framework-bom</artifactId>
            <version>${version.axon}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

        ...

    </dependencies>
</dependencyManagement>
<!--...-->
----
--

Gradle::
+
--

For usage with *Gradle Version 4.x* and below, apply the dependency-management-plugin like so:

[source,groovy]
----
buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath "io.spring.gradle:dependency-management-plugin:0.5.1.RELEASE"
  }
}

apply plugin: "io.spring.dependency-management"
----

After this, import the Axon BOM:

[source,groovy]
----
dependencyManagement {
  imports {
    mavenBom 'io.axoniq.framework:axoniq-framework-bom:<VERSION>'
  }
}
----

Beginning with *https://docs.gradle.org/5.0/userguide/managing_transitive_dependencies.html#sec:bom_import[Gradle version 5.0]*, you can also omit the dependency-management plugin and instead use the `platform` dependency DSL to import maven BOMs:

`implementation(platform("io.axoniq.framework:axoniq-framework-bom:<VERSION>"))`
--
====

After that is in place, you can add any of the mentioned dependencies from the <<Advanced framework modules, advanced modules>> without specifying versions.
Furthermore, you will be guaranteed that the provided versions in the BOM are compatible with one another.

[NOTE]
====
The advanced framework BOM includes all dependencies for the xref:ROOT:modules.adoc#_main_modules[base framework modules] and the xref:ROOT:modules.adoc#_extension_modules[base framework extension modules], so whenever you use the advanced framework BOM you do not need to additionally include the xref:ROOT:modules.adoc#base-framework-bom[base framework BOM].
====
